### ISSUE TITLE
Why include as a dependency?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [alrra/travis-after-all#12]
Doesn't seem worthwhile to include it as a dependency, when it makes no sense outside the context of Travis; why not suggest a method like this?

```
after_script:
  - |
      npm install 'travis-after-all@^1.4.0'
      $(nam bin)/travis-after-all && npm run-script build-succeeded
```

Am I missing something important? (=

**Comment by alrra** [comment]
> `npm install 'travis-after-all@^1.4.0'`
> 
> why not suggest a method like this? 

@ELLIOTTCABLE Mainly because that would make most people forget about that line and not upgrade to a newer (major) version, especially if they rely on tools like [David](https://david-dm.org) or [Greenkeeper](http://greenkeeper.io/) to notify them about new releases.

**Comment by ELLIOTTCABLE** [comment]
Hm. `npm config get travis-after-all-version`, or something; so that it can be stored in one centralized place, but not get installed outside of Travis?

**Comment by alrra** [comment]
> Hm. `npm config get travis-after-all-version`, or something

@ELLIOTTCABLE Can you elaborate? Thanks!
