### ISSUE TITLE
travis-after-all produces no more output after one of the jobs fail, but doesn't exit, failing the build

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [alrra/travis-after-all#13]
So, the `travis-after-all`-assigned ‘leader’ was waiting for the last jobs in the build to complete; but when they failed … it never exited:

https://travis-ci.org/ELLIOTTCABLE/Paws.js/jobs/96397639#L986

So _that_ job ‘failed’ as well, due to lack of output, even though the test-scripts _did_ succeed.

**Comment by alrra** [comment]
@ELLIOTTCABLE Thanks for opening this issue!

I'll look into it as soon as I have some free time.

**Comment by DoumanAsh** [comment]
Has been playing with this script and noticed the same issue.

**Comment by mdreizin** [comment]
I also have the same issue https://travis-ci.org/mdreizin/webpack-config/jobs/143517972

**Comment by alrra** [comment]
Note: I've deprecated this project as the functionality it provided is now supported natively by `Travis CI` via [`Build Stages`](https://blog.travis-ci.com/2017-05-11-introducing-build-stages).
