### ISSUE TITLE
Documentation issue: npm is not installed on all Travis workers

### ISSUE THREAD

**Issue by mernst** [alrra/travis-after-all#16]
The documentation says,

> Note: travis-after-all is written in JavaScript, however, since Travis includes the Node runtime by default, it can be use no matter what build environment you have.

However, if you use `language: generic` in your `.travis.yml`, then npm is not installed and you get an error

```
$ npm install --save-dev travis-after-all
The program 'npm' is currently not installed. To run 'npm' please ask your administrator to install the package 'npm'
The command "npm install --save-dev travis-after-all" failed and exited with 127 during .
```
(For an example, see https://travis-ci.org/codespecs/daikon/jobs/144684847 .)

Interestingly, using `language: java` is enough to guarantee that npm is installed.

**Comment by alrra** [comment]
> However, if you use `language: generic` in your `.travis.yml`, then **`npm` is not installed**

@mernst [It is](https://docs.travis-ci.com/user/ci-environment/#Runtimes), and here is a quick example to demonstrate that.

Having only the following in the [`.travis.yml`](https://github.com/alrra/test-travis-npm-language-generic/blob/3e95f3a60b8302fec77afb9bc46a0a2a2bc4c062/.travis.yml) file:

```yml
language: generic

script:
  - npm --version
```

the build will produce [this output](https://travis-ci.org/alrra/test-travis-npm-language-generic/builds/146842749#L125):

```bash
# ...
$ npm --version
1.4.28
# ...
```
