### ISSUE TITLE
travis-after-all times out and fails jobs

### ISSUE THREAD

**Issue by mernst** [alrra/travis-after-all#18]
travis-after-all makes one of the jobs wait until all of the other jobs have completed.  This causes an overall build failure when the wall clock time exceeds 50 minutes.  This is a show-stopper for me.

As an example, consider
https://travis-ci.org/codespecs/daikon/builds/144686559

Each Travis job is limited to 50 minutes, but the overall wall clock time for the entire build was about an hour.  That's because there were more jobs in the build than there are available executors, so some of the jobs didn't start until after other builds had finished.  By that time, the [`after_script:` block](https://github.com/codespecs/daikon/blob/970f6fc63806882c635c7fd02ac90c4bf403bb9c/.travis.yml#L42) of the first job, where travis-after-all was running, had [timed out](https://travis-ci.org/codespecs/daikon/jobs/144686560#L8553) and was marked as a failure.  Therefore, the entire build was marked as a failure, even though every job passed (other than the `travis-after-all` invocation in the `after_script:` block).

Perhaps this can be fixed by choosing the last job instead of the first as the leader.  By the time any job completes and its `after_script:` block executes, all jobs should exist (even if they haven't started executing yet), so this information will be available via the API and every job will get a consistent view of it.

**Comment by alrra** [comment]
Note: I've deprecated this project as the functionality it provided is now supported natively by `Travis CI` via [`Build Stages`](https://blog.travis-ci.com/2017-05-11-introducing-build-stages).
