### ISSUE TITLE
Failed to parse JSON from "https://api.travis-ci.org/jobs/147525158". Error: Unexpected token F

### ISSUE THREAD

**Issue by gr2m** [alrra/travis-after-all#21]
See https://github.com/semantic-release/semantic-release/issues/265. I *think* this is an issue within `travis-after-all`. I’m happy to help dig into it, I’d appreciate pointers / ideas of how to debug it

**Comment by gr2m** [comment]
workes again, see https://github.com/semantic-release/semantic-release/issues/265

**Comment by alrra** [comment]
From https://github.com/semantic-release/semantic-release/issues/265:

> Turns out the API call to https://api.travis-ci.org/jobs/147525158 returns `Forbidden`. Any idea why that might happen?

@gr2m That might have been due to a [service outage](https://blog.travis-ci.com/2016-07-27-service-outages), or Travis CI may have changed something related to the number of requests you can do to their API? 😕

**Comment by gr2m** [comment]
There was no documented service outage during this time, I double checked. I pinged Travis support about it, let’s see what they have to say :)

**Comment by alrra** [comment]
>  I pinged Travis support about it, let’s see what they have to say :)

@gr2m Great, thanks! :)
