### ISSUE TITLE
`travis-after-all` seems to wait forever

### ISSUE THREAD

**Issue by izaid** [alrra/travis-after-all#5]
So, travis-after-all seems like a great project, but I'm having issues making it actually work. Here's my setup.

I'm one of the lead developers on the libdynd project (https://github.com/libdynd/libdynd), with a .travis.yml at https://github.com/libdynd/libdynd/blob/master/.travis.yml.

In that file, we have 5 quite different builds and would like to execute a script after all of them are complete. To attempt to make this work, I added the following to one of the builds:

```yml
after_script:
    - declare exitCode
    - curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.3.0/lib/travis-after-all.js | node
    - exitCode=$?
    - if [ $exitCode -eq 0 ]; then echo "all passed"; fi
```

Unfortunately, this seems to just hang forever. At the end of the specific build it is attached to, it will say "[travis-after-all] Job succeeded" then "[travis-after-all] Waiting for 2551.1, 2551.2 and 2551.4 to be done...", which will repeat forever. See https://travis-ci.org/libdynd/libdynd/jobs/80180265 for example.

Am I using this wrong? Or is this a bug?

**Comment by alrra** [comment]
>  Or is this a bug? 

See https://github.com/alrra/travis-after-all/issues/4.

> - curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.3.0/lib/travis-after-all.js | node

@izaid "Update" to the latest version, e.g. use:

```
curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.1/lib/travis-after-all.js | node
```

--

Let me know how it went!

**Comment by alrra** [comment]
@izaid Also, can you use the following:

```yml
after_script:
  - |

      declare exitCode

      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.1/lib/travis-after-all.js | node
      exitCode=$?

      if [ $exitCode -eq 0 ]; then
        echo "all passed"; 
        # Here goes the code that needs to be executed if the build succeeded
      fi
```

**Comment by izaid** [comment]
Thanks for the quick reply!

Okay, so I just retried this with your latest suggestion. The good news is that I now get:

[travis-after-all] Job succeeded (d27e84f083ae6acaedf2a8468da07a68e43db241c7497e631be6229daf79de68)
[travis-after-all] Some other job was assigned to do the task

However, I'm unable to find the output "all passed" in any of the builds. Is something wrong? Or is it weird that I'm using echo?

**Comment by alrra** [comment]
@izaid Move `after_script` outside of the `matrix` ([it shouldn't be there](http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle)), and it will work (see: https://github.com/alrra/libdynd/commit/3e42869a8f5dcfb06dfa5b7af34ea8253569b7d0 and https://travis-ci.org/alrra/libdynd/builds/80185388).

**Comment by alrra** [comment]
@izaid Better yet, see:

* https://travis-ci.org/alrra/libdynd/jobs/80185389#L2800
* https://travis-ci.org/alrra/libdynd/jobs/80185390#L2720
* https://travis-ci.org/alrra/libdynd/jobs/80185391#L2979
* https://travis-ci.org/alrra/libdynd/jobs/80185392#L2724
* https://travis-ci.org/alrra/libdynd/jobs/80185393#L3607

**Comment by alrra** [comment]
> ```yml
after_script: 
  - declare exitCode
  - curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.3.0/lib/travis-after-all.js | node
  - exitCode=$?
  - if [ $exitCode -eq 0 ]; then echo "all passed"; fi
```

@izaid I forgot to explain why [I said](https://github.com/alrra/travis-after-all/issues/5#issuecomment-139971526) you should use something different then the above code.

The problem with the above is that, since you are using `- commands`,  Travis CI won't keep the values of the variables from one line to another.

**Comment by izaid** [comment]
Great, I can confirm this works now if I move after_script outside of the build matrix. This is enough for me, I can make things work like that.

However, it actually is valid to have after_script inside the build matrix. Is this that travis-after-all should support?

And thanks a lot for your help! This tool is very useful.

**Comment by alrra** [comment]
>  I can [confirm](https://travis-ci.org/libdynd/libdynd/builds/80186762) this works now if I move after_script outside of the build matrix.

@izaid Thanks for letting me know!

>  Isn't this something that travis-after-all should support?

Well, it does support that, you just need to include the [`after_script` code](https://github.com/alrra/travis-after-all/issues/5#issuecomment-139971526) in **all** the `include`s from the matrix. Basically, in order for `travis-after-all` to work, it needs to be executed by **all** jobs.

**Comment by izaid** [comment]
Great, thanks for the explanation. I'm very happy with this.
