### ISSUE TITLE
Configurable Travis CI API endpoint

### ISSUE THREAD

**Issue by boennemann** [alrra/travis-after-all#6]
Hey @alrra,

it would be cool if users could define the Travis CI API endpoint that should be used.
Currently this module won't work with private/enterprise Travis versions.

The python version solves this with arguments passed: https://github.com/dmakhno/travis_after_all/blob/master/travis_after_all.py#L22-L23
I think this could be configureable with environment variables, or options passed to the `require`d module.

Please let me know what you think; I'm happy to help to get this going.

Best,
Stephan

**Comment by gr2m** [comment]
We are affected by this as well, we use Travis Pro for our private repositories at https://github.com/ehealthafrica/. Thanks @boennemann for finding the root cause for the problem. I'm also happy to help get this resolved, but need guidance

**Comment by alrra** [comment]
@boennemann, @gr2m Sorry for the delayed answer. 

> it would be cool if users could define the Travis CI API endpoint that should be used.
Currently this module won't work with private/enterprise Travis versions.
>
> The python version solves this with arguments passed: https://github.com/dmakhno/travis_after_all/blob/master/travis_after_all.py#L22-L23

From http://docs.travis-ci.com/api/#overview: 

> The first thing you will have to find out is the correct API endpoint to use.

>  * Travis CI for open source: For open source projects tested on travis-ci.org, use https://api.travis-ci.org.
>  * Travis Pro: For private projects tested on travis-ci.com, use https://api.travis-ci.com.
>  * Travis Enterprise: For projects running on a custom setup, use https://travis.example.com/api (where you replace travis.example.com with the domain Travis CI is running on).

> **Note that both Pro and Enterprise will require almost all API calls to be authenticated.**

@boennemann :arrow_up: It seems that the authentication part also needs to be done.

--

> I think this could be configureable with environment variables, or options passed to the required module.

@boennemann Personally, I'm not a big fan of environment variables, so maybe have something like:

```js
var configs = {
    "travis-api-endpoint": "https://api.travis-ci.org" 
};

// ...

travisAfterAll(callback, configs);
```

and 

```bash
node -e "$(curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/x.x.x/lib/travis-after-all.js)" travis-api-endpoint="https://api.travis-ci.org" 
```

--

@boennemann, @gr2m Unfortunately, I won't have the time to look into this in the next few days. Also, I do not have a Pro/Enterprise account, so I will need your help to test it. 

Pull requests are also very welcomed!

**Comment by alrra** [comment]
The functionality this project provided is now supported natively by `Travis CI` via [`Build
Stages`](https://blog.travis-ci.com/2017-05-11-introducing-build-stages).
